server:
  port: 3004
  error:
    include-message: always
    include-binding-errors: always
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/account
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
