server:
  port: 3004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
spring:
  data:
    monogodb:
      database: account
      host: localhost
      port: 27017
      #authentication-database: admin
      #username: root
      #password: root
