server:
  port: 3004
  error:
    include-message: always
    include-binding-errors: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
spring:
  data:
    monogodb:
      uri: mongodb://localhost:27017/account
