server:
  port: 3004
  error:
    include-message: always
    include-binding-errors: always
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:3007
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/account
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
