server:
  port: 3002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-jpa
          uri: lb://customer-jpa
          predicates:
            - Path=/customers/**
        - id: customer-jpa
          uri: lb://account-bank
          predicates:
            - Path=/accounts/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/credits/**, /cards/**, /movements/**
