server:
  port: 3002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customers/**
        - id: account
          uri: lb://account
          predicates:
            - Path=/accounts/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/credits/**,/cards/**
        - id: transaction
          uri: lb://transaction
          predicates:
            - Path=/transactionAccount/**,/transactionCard/**,/transactionCredit/**,/TransferController/**
