server:
  port: 3005
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/credit
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
