server:
  port: 3005
  error:
    include-message: always
    include-binding-errors: always
spring:
  boot:
    admin:
      client:
        url: http://localhost:3007
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/credit
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
