server:
  port: 3003
spring:
  data:
    auto-index-creation: true
    mongodb:
      uri: "mongodb://localhost:27017/customer"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
