server:
  port: 3006
  error:
    include-message: always
    include-binding-errors: always
spring:
  boot:
    admin:
      client:
        url: http://localhost:3007
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transaction
    username: root
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
