server:
  port: 3002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-jpa
          uri: lb://customer-jpa
          predicates:
            - Path=/api/v1/customers/**
