server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka
spring:
  cloud:
    gateway:
      discovery:
          enabled: true
      routes:
        - id: CUSTOMER-JPA
          uri: http://CUSTOMER-JPA
          predicates:
            - Path=/customers/**
