server:
  port: 3003
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:3001/eureka
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password:123456
