server:
  port: 3003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/client
    username: root
    password:
